import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma.service';
import { EventEmitter2 } from '@nestjs/event-emitter';
import { createReadStream, existsSync } from 'fs';
import { join, extname } from 'path';

@Injectable()
export class ContentEngineService {
  readonly logger = new Logger(ContentEngineService.name);

  constructor(
    private prisma: PrismaService,
    private eventEmitter: EventEmitter2
  ) {}

  /** Create asset record after a real file upload */
  async createAssetRecord(data: {
    topicId: string;
    tenantId: string;
    type: string;
    physicalPath: string;
    fileSize: number;
    originalName: string;
    initialStatus?: string;
  }) {
    const asset = await this.prisma.extendedClient.assetMetadata.create({
      data: {
        topic: { connect: { id: data.topicId } },
        type: data.type as any,
        status: (data.initialStatus || 'UPLOADING') as any,
        physical_path: data.physicalPath,
        original_name: data.originalName,
        file_size: data.fileSize,
        tenant_id: data.tenantId,
      },
    });

    // Emit upload event
    this.eventEmitter.emit('content.uploaded', {
      asset_id: asset.id,
      type: data.type,
      tenant_id: data.tenantId,
      topic_id: data.topicId,
    });

    return asset;
  }

  /** Get asset metadata by topic */
  async getAssetByTopic(topicId: string) {
    return this.prisma.extendedClient.assetMetadata.findUnique({
      where: { topic_id: topicId },
      include: { video_metadata: true }
    });
  }

  /** Remove an asset record (used when a re-upload replaces the old one). */
  async deleteAsset(assetId: string) {
    return this.prisma.extendedClient.assetMetadata.delete({ where: { id: assetId } });
  }

  /** Topic + its lesson/module/course chain — used to place uploads in the
   *  right uploads/{tenant}/{course}/{module}/{lesson}/ directory. */
  async getTopicContext(topicId: string) {
    return this.prisma.extendedClient.topic.findUnique({
      where: { id: topicId },
      include: { lesson: { include: { module: { include: { course: true } } } } },
    });
  }

  /** Full processing pipeline: SCANNING → PROCESSING → READY */
  async processVideo(assetId: string) {
    this.logger.log(`Starting processing pipeline for asset ${assetId}`);

    const asset = await this.prisma.extendedClient.assetMetadata.findUnique({ where: { id: assetId } });
    if (!asset) throw new NotFoundException('Asset not found');

    // 1. SCANNING (ClamAV stub)
    await this.updateStatus(assetId, 'SCANNING');
    this.eventEmitter.emit('content.scanning', { asset_id: assetId });
    await this.delay(100);

    // 2. PROCESSING (FFmpeg HLS stub)
    await this.updateStatus(assetId, 'PROCESSING');
    this.eventEmitter.emit('content.processing', { asset_id: assetId });
    await this.delay(200);

    // 3. Create VideoMetadata with HLS stub paths
    // In production: spawn FFmpeg → generate master.m3u8 + segments
    const existingMeta = await this.prisma.extendedClient.videoMetadata.findUnique({ where: { asset_id: assetId } });
    if (!existingMeta) {
      await this.prisma.extendedClient.videoMetadata.create({
        data: {
          asset_id: assetId,
          thumbnail_path: `/uploads/thumbnails/${assetId}.jpg`,
          preview_path: `/uploads/previews/${assetId}-preview.mp4`,
          // HLS master playlist - in production this is generated by FFmpeg
          hls_stream_url: asset.physical_path
            ? `/uploads/hls/${assetId}/master.m3u8`
            : `https://cdn.example.com/videos/${assetId}/master.m3u8`,
          duration_seconds: 0, // would be set by ffprobe
          tenant_id: asset.tenant_id,
        }
      });
    }

    // 4. READY
    const ready = await this.updateStatus(assetId, 'READY');
    this.eventEmitter.emit('content.ready', { asset_id: assetId, tenant_id: asset.tenant_id });
    this.logger.log(`Asset ${assetId} is READY`);
    return ready;
  }

  /** SCORM package handler - extracts and returns index path */
  async processScorm(assetId: string) {
    const asset = await this.prisma.extendedClient.assetMetadata.findUnique({ where: { id: assetId } });
    if (!asset) throw new NotFoundException('Asset not found');

    // In production: use 'adm-zip' to extract zip and locate imsmanifest.xml
    // Stub: mark as READY and set path
    return this.updateStatus(assetId, 'READY');
  }

  /** Legacy stub method kept for backward compatibility */
  async initiateVideoUpload(topicId: string, tenantId: string) {
    return this.createAssetRecord({
      topicId,
      tenantId,
      type: 'VIDEO',
      physicalPath: '',
      fileSize: 0,
      originalName: 'stub-upload',
    });
  }

  private async updateStatus(assetId: string, status: any) {
    return this.prisma.extendedClient.assetMetadata.update({
      where: { id: assetId },
      data: { status },
    });
  }

  private delay(ms: number) {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
}
